# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-jast8_Z1PK_gvUMnwOc3k784BYUXlj9

# Listas
"""

lista = [1,'dos',3.2,5]
lista

"""### 1) `append(x)`

Agregar un item al final de la lista.
"""

lista.append('x') 
lista
#equivalente a lista[len(lista):]=['x']

"""### 2) `extend(iterable)`

Extiende la lista agregando todos los elementos que se le agregen en el argumento iterable.
"""

lista.extend([1,2])
lista
#equivalente a lista[len(lista):]=['x']

"""### 3) `insert(i,x)`

Inserta un item en la posición dada. El primer argumento corresponde al índice del elemento donde se va a insertar el item.
"""

lista.insert(1,'a')
lista
#lista.insert(len(lista),'a') es equivalente a lista.append('a')

"""### 4) `remove(x)`
Eliminia el primer item de la lista que es igual a el argumento x, y devuelve `ValueError` si no hay items iguales a dicho valor.
"""

lista.remove('a') 
lista

"""### 5) `pop(i)`

Elimina el item de la posición dada y devuelve dicho valor. Si no se específica la posición elimina y devuelve el último item de la lista.
"""

lista.pop(2)
lista

"""### 6) `clear()`

Elimina todos los items de la lista.
"""

lista.clear()
lista
#equivalente a del lista[:]

"""### 7) `index(x[,start[,end]])`

Devuelve el índice basado en cero de la lista cuyo primer valor es igual a x, devuelve un ValueError si no se encutra dicho valor. Los argumentos start y end son opcionales y se usan para limitar la busqueda en una subsecuencia de la lista.
"""

lista = [1,'dos',3.2,5]
lista.index('dos')

"""### 8) `count(x)`

Revuelve el número de veces que se encuentra el elemento x en la lista.
"""

lista.count('dos')

"""### 9) `sort(key=None, reverse=False)`

ordena los items de la lista.
"""

lista1 = [1,5,8,9,63.2,52.1,47.2]
lista1.sort()
lista1

"""### 10) `reverse()`
Devuelve los elementos de la lista en forma reversa.
"""

lista.reverse()
lista

"""### 11) `copy()`

Devuelve una copia superficial de la lista.
"""

lista2 = lista.copy()
lista2

"""## EJEMPLO"""

fruits = ['orange', 'apple', 'pear', 'banana', 'kiwi', 'apple', 'banana']
fruits
#cuántas veces aparece 'apple en la lista'
fruits.count('apple')
#En qué indice se encuentra 'banana'
fruits.index('banana')
#Encuentre el indice después de la posicion 4 que se encuentre 'banana'
fruits.index('banana',4)
#Colocar en forma reversa la lista fruits
fruits.reverse()
fruits
#Agregar en la última posición 'grape'
fruits.append('grape')
fruits
#Ordenar los elementos de la lista
fruits.sort()
fruits
#Eliminar el último item de la lista fruits
fruits.pop()
fruits

stack = [3, 4, 5]
#Agregar el número 6
stack.append(6)
#Agregar el número 7
stack.append(7)
stack

stack.pop()
stack.pop()
stack.pop()
stack

